"""add display name

Revision ID: 671d3cb4b8d6
Revises: ccef1a1a77ab
Create Date: 2026-03-20 17:28:37.400664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671d3cb4b8d6'
down_revision: Union[str, Sequence[str], None] = 'ccef1a1a77ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'display_name')
    # ### end Alembic commands ###
